routes/web.php
 <?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\UploadVideoController;
use App\Http\Controllers\VideoController;
use App\Http\Controllers\VoteController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')
        ->name('home');

Route::resource('channels', 'ChannelController');

Route::get('videos/{video}', [VideoController::class, 'show'])
        ->name('videos.show');
Route::put('videos/{video}', [VideoController::class, 'updateViews']);
Route::get('videos/{video}/comments', [CommentController::class, 'index']);
Route::get('comments/{comment}/replies', [CommentController::class, 'show']);
Route::put('videos/{video}/update', [VideoController::class, 'update'])
        ->middleware(['auth'])
        ->name('videos.update');

Route::middleware(['auth'])->group(function() {
    Route::post('comments/{video}', [CommentController::class, 'store']);

    Route::post('votes/{entityId}/{type}', [VoteController::class, 'vote']);

    Route::post('channels/{channel}/videos', [UploadVideoController::class, 'store']);

    Route::get('channels/{channel}/videos', [UploadVideoController::class, 'index'])
            ->name('channel.upload');

    Route::resource('channels/{channel}/subscriptions', 'SubscriptionController')
            ->only(['store', 'destroy']);
});

app/Channel.php
<?php

namespace App;

use App\Subscription;
use App\Video;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Channel extends Model implements HasMedia
{
    use HasMediaTrait;

    public function user() :BelongsTo
    {
        return $this->belongsTo(User::class);
    }
    
    public function registerMediaConversions(?Media $media = null)
    {
        $this->addMediaConversion('thumb')
                ->width(100)
                ->height(100);
    }

    public function image() :?string
    {
        if ($this->media->first()) {
            return $this->media->first()->getFullUrl('thumb');
        }

        return null;
    }
    
    public function editable() :bool
    {
        if (!auth()->check()) {
            return false;
        }

        return $this->user_id == auth()->user()->id;
    }

    public function subscriptions() :HasMany
    {
        return $this->hasMany(Subscription::class);
    }

    public function videos() :HasMany
    {
        return $this->hasMany(Video::class);
    }
}

app/Http/Controllers/ChannelController.php
<?php

namespace App\Http\Controllers;

use App\Channel;
use App\Http\Requests\Channels\UpdateChannelRequest;
use Illuminate\Http\Request;

class ChannelController extends Controller
{
    public function __construct()
    {
        /**
         * Middleware goes here instead of the routes definition 
         * in web.php because it is just for this route. 
         * If it went on the route definition, with it being a 'resource' 
         * type route definition, it would apply for all resource's CRUD 
         * routes.
         */
        $this->middleware(['auth'])->only('update');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  Channel  $channel
     * @return \Illuminate\Http\Response
     */
    public function show(Channel $channel)
    {
        $videos = $channel->videos()->paginate(5);

        return view('channels.show', compact('channel', 'videos'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateChannelRequest  $request
     * @param  Channel  $channel
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateChannelRequest $request, Channel $channel)
    {
        if($request->hasFile('image')) {
            $channel->clearMediaCollection('images');
            $channel->addMediaFromRequest('image')
                ->toMediaCollection('images');
        }

        $channel->update([
            'name'        => $request->name,
            'description' => $request->description
        ]);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/channels/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    {{ $channel->name }}
                    <a href="{{ route('channel.upload', $channel->id) }}">Upload videos</a>
                </div>

                <div class="card-body">
                    @if($channel->editable())
                        <form id="update-channel-form" 
                        action="{{ route('channels.update', $channel->id) }}" 
                        method="POST" 
                        enctype="multipart/form-data">
                        @csrf
                        @method('PATCH')
                    @endif

                        <div class="form-group row justify-content-center">
                            <div class="channel-avatar">
                                
                                @if($channel->editable())
                                    <div class="channel-avatar-overlay"
                                        onclick="document.getElementById('image').click()">
                                        <svg xmlns="http://www.w3.org/2000/svg" 
                                             xmlns:xlink="http://www.w3.org/1999/xlink" 
                                             version="1.1" 
                                             id="Layer_1" 
                                             x="0px" 
                                             y="0px" 
                                             width="50px" 
                                             height="50px" 
                                             viewBox="0 0 512 512" 
                                             enable-background="new 0 0 512 512" 
                                             xml:space="preserve">
                                            <g fill="#fff">
                                                <circle cx="255.811" 
                                                    cy="285.309" 
                                                    r="75.217"/>
                                                <path d="M477,137H352.718L349,108c0-16.568-13.432-30-30-30H191c-16.568,0-30,13.432-30,30l-3.718,29H34   c-11.046,0-20,8.454-20,19.5v258c0,11.046,8.954,20.5,20,20.5h443c11.046,0,20-9.454,20-20.5v-258C497,145.454,488.046,137,477,137   z M255.595,408.562c-67.928,0-122.994-55.066-122.994-122.993c0-67.928,55.066-122.994,122.994-122.994   c67.928,0,122.994,55.066,122.994,122.994C378.589,353.495,323.523,408.562,255.595,408.562z M474,190H369v-31h105V190z"/>
                                            </g>
                                        </svg>
                                    </div>
                                @endif
                                
                                <img src="{{ $channel->image() }}" alt="">
                                
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <h4 class="text-center">
                                {{ $channel->name }}
                            </h4>
                            
                            <p class="text-center">
                                {{ $channel->description }}
                            </p>
                             
                            <div class="text-center">
                                <subscribe-button :channel="{{ $channel }}"
                                    :initial-subscriptions="{{ $channel->subscriptions }}"/>
                            </div>
                            
                        </div>
                        
                        @if($channel->editable())
                            <input id="image" 
                                type="file" 
                                name="image"
                                style="display: none;"
                                onchange="document.getElementById('update-channel-form').submit()">

                            <div class="form-group">
                                <label for="name" 
                                    class="form-control-label">
                                    Name
                                </label>
                                <input type="text"
                                    class="form-control"
                                    id="name"
                                    name="name"
                                    value="{{ $channel->name }}">
                            </div>

                            <div class="form-group">
                                <label for="description" 
                                    class="form-control-label">
                                    Description
                                </label>
                                <textarea class="form-control"
                                    id="description"
                                    name="description"
                                    rows="3"
                                    >{{ $channel->description }}</textarea>
                            </div>
                        
                            @if($errors->any())
                            <ul class="list-group mb-5">
                                @foreach($errors->all() as $error)
                                    <li class="text-danger list-group-item">
                                        {{ $error }}
                                    </li>
                                @endforeach
                            </ul>
                            @endif

                            <button class="btn btn-info"
                                type="submit">
                                Update channel
                            </button>
                        @endif

                    @if($channel->editable())
                        </form>
                    @endif
                </div>
            </div> 
            
            <div class="card">
                <div class="card-header">
                    Videos
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Views</th>
                            <th>Status</th>
                            <th></th>
                        </thead>

                        <tbody>
                            @foreach($videos as $video)
                                <tr>
                                    <td>
                                        <img src="{{ $video->thumbnail }}" 
                                            alt=""
                                            width="40px"
                                            height="40px">
                                    </td>
                                    <td>{{ $video->title }}</td>
                                    <td>{{ $video->views }}</td>
                                    <td>
                                        {{ $video->percentage === 100 ? "Live" : "Processing" }}
                                    </td>
                                    <td>
                                        @if($video->percentage === 100)
                                            <a href="{{ route('videos.show', $video->id) }}"
                                                class="btn btn-sm btn-info">View</a>
                                        @endif
                                    </td>

                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    
                    <div class="row justify-content-center">
                        {{ $videos->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/channels/upload.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <channel-uploads :channel="{{ $channel }}" 
            inline-template>
            <div class="col-md-8">
                <div class="card p-3 d-flex justify-content-center align-items-center"
                    v-if='!selected'>
                    <svg onclick="document.getElementById('video-files').click()"
                        xmlns="http://www.w3.org/2000/svg" 
                        xmlns:xlink="http://www.w3.org/1999/xlink" 
                        xmlns:v="https://vecta.io/nano" 
                        viewBox="0 0 170 170"
                        width="100px"
                        height="100px">
                        <path xmlns="http://www.w3.org/2000/svg" 
                            d="M154.3 17.5a19.6 19.6 0 0 0-13.8-13.8C128.4.4 79.7.4 79.7.4S31 .5 18.9 3.8A19.6 19.6 0 0 0 5.1 17.6C1.44 39.1.02 71.86 5.2 92.5A19.6 19.6 0 0 0 19 106.3c12.1 3.3 60.8 3.3 60.8 3.3s48.7 0 60.8-3.3a19.6 19.6 0 0 0 13.8-13.8c3.86-21.53 5.05-54.27-.1-75z" 
                            fill="red"/>
                        <path xmlns="http://www.w3.org/2000/svg" 
                            fill="#fff" 
                            d="M64.2 78.4L104.6 55 64.2 31.6z"/>
                    </svg> 
                    
                    <input type="file" 
                        ref="videos"
                        id="video-files"
                        style="display: none;"
                        @change="upload"
                        multiple>
                    
                    <p class="text-center">Upload videos</p>
                </div> 
                
                <div class="card p-3"
                    v-else>
                    <div class="my-4" v-for="video in videos">
                        <div class="progress mb-3">
                            <div class="progress-bar progress-bar-striped progress-bar-animated"
                                role="progressbar"
                                :style="{ width: `${video.percentage || progress[video.name]}%` }" 
                                aria-valuenow="50"
                                aria-valuein="0"
                                aria-valuemax="100">
                                @{{ video.percentage ? video.percentage == 100 ? 'Processing Complete' : 'Processing' : 'Uploading' }}
                            </div>
                        </div>
                            
                        <div class="row">
                            <div class="col-md-4">
                                <div v-if="!video.thumbnail"
                                    class="d-flex justify-content-center align-items-center"
                                    style="height: 180px; color: white; font-size: 18px; background: #808080;">
                                         Loading thumbnail ...
                                </div>
                                <img v-else 
                                    :src="video.thumbnail"
                                    alt=""
                                    style="width: 100%;">
                            </div>
                            <div class="col-md-4">
                                <a v-if="video.percentage && video.percentage == 100"
                                    :href="`/videos/${video.id}`"
                                    target="_blank">
                                    @{{ video.title }}
                                </a>
                                <h4 v-else
                                    class="text-center">
                                    @{{ video.title || video.name }}
                                </h4>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </channel-uploads>
    </div>
</div>
@endsection